CREATE TABLE Measurement(
                            measurement_id int GENERATED BY DEFAULT AS IDENTITY,
                            sensor_id int REFERENCES Sensor(sensor_id) ON DELETE SET NULL DEFAULT NULL,
                            value float NOT NULL,
                            raining bool NOT NULL,
                            measured_at timestamp NOT NULL
);

SELECT * FROM Measurement;
TRUNCATE TABLE Measurement;
DROP TABLE Measurement;

CREATE TABLE Sensor(
                       sensor_id int GENERATED BY DEFAULT AS IDENTITY UNIQUE,
                       name varchar NOT NULL
);

SELECT * FROM Sensor;
DROP TABLE Sensor;